### ISSUE TITLE
Remove `app/helpers/read-path.js`

### ISSUE THREAD

**Issue by GavinJoyce** [novafloss/ember-simple-select#11]
It looks like [app/helpers/read-path.js](https://github.com/novafloss/ember-simple-select/blob/master/app/helpers/read-path.js) wasn't removed from https://github.com/novafloss/ember-simple-select/pull/10 which results in a boot time error when using `0.6.0`

**Comment by jelhan** [comment]
It's definitely not needed anymore and should have been removed by #10. But I'm not quite sure if your boot time error is caused by it. I'm using ember-simple-select 0.6.0 with ember-cli 2.4.2 and didn't see any error.

**Comment by xcambar** [comment]
@GavinJoyce Feel free to close the issue now that https://github.com/novafloss/ember-simple-select/pull/13 by @jelhan has been merged.

**Comment by GavinJoyce** [comment]
Nice, thanks! 🍻
