### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated.

### ISSUE THREAD

**Issue by jelhan** [novafloss/ember-simple-select#15]
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
    at Function.Addon.lookup (/Users/dillonwelch/Code/Work/currica/nsqip-web-ember/node_modules/ember-cli/lib/models/addon.js:896:27)
```

ember-simple-select 0.6.0 has ember-cli-htmlbars 0.7.9 as dependency, which is causing this deprecation warning. Updating ember-cli-htmlbars to 1.x fixes this issue. Was already done by 3832bf8d30010f2fdd6f2dfd4ca63331fa2451c5. Could you please release a patch version therefore?

**Comment by andyhot** [comment]
Is it possible to release perhaps a 0.6.1 version of this?

**Comment by xcambar** [comment]
Done!

That should not have taken so long. Please accept our apologies.
