### ISSUE TITLE
Selection is not working on a list of objects

### ISSUE THREAD

**Issue by temecom** [novafloss/ember-simple-select#6]
The selection does not work when a list of model object is used to to build the list. 

The line of code at: /addon/components/simple-select.js

Line 40:    

const selection = this.get(`content.${contentIndex}`) || null;

returns null always - content is an array of model objects to the . operator does not work. You need to use: 

 const selection = this.get(`content`).objectAt(contentIndex) || null;

Then it works. 

As a side note: the 'value' attribute needs to be the id of the selected object in order to correctly select the item. eg: 

{{simple-select
        content=dataSets
        optionValuePath="id"
        optionLabelPath="label"
        value=dataRecord.dataSet.id
        prompt="Please select a data set"
        action='dataSetSelected'
      }}

**Comment by xcambar** [comment]
Thanks, you're correct. `ObjectAt` is a more idiomatic to the use case at hand. Code will be updated (but PRs are always welcome :wink: ).

There's quite some confusion as to `value` and `selection` parameters: 
* `value` is for the ID of the selected object (as you noticed)
* `selection` is the selected object itself

Both have valid use cases, but to be honest, the naming here is pretty poor, IMO. If you have some alternatives to offer, I'm all ears :smile:

**Comment by temecom** [comment]
Thank You Xavier

I will clone and add any changes next time. I think that a bootstrap-ish 
version would be nice. I can explore that.

It may just be a matter of applying a bootstrap-sass class to the 
component.

On the selection/value confusion... I think that a truly 'simple' select 
would be:

{{simple-select
     content=myListOfObjects
     value=myTargetObject.someProperty
}}

The over-ridable defaults would be:

     optionValuePath="id"
     optionLabelPath="name|label"
     prompt="Please select a value"
     action=automatically populate myTargetObject.someProperty


It would also be nice to use the less ambiguous 'items' as an alias for 
content.

I will explore this as well.

Chris
